import type { SkillFamily } from './Stage';
import catalog from './skill-catalog.json';

type CatalogEntry = { family: string; label: string };
const CATALOG = catalog as Record<string, CatalogEntry>;

/**
 * SkillCatalog — loaded from skill-catalog.json, which is generated by
 * scripts/generate-skill-catalog.py from practices/*/skills/*/SKILL.md.
 *
 * To add or update a skill: edit the SKILL.md front matter in the practices
 * folder, then re-run:
 *   python scripts/generate-skill-catalog.py
 */
export class SkillCatalog {
  private static readonly FAMILY_CSS: Record<SkillFamily, string> = {
    'domain-driven-design':             'aad-fam-ddd',
    'user-experience-design':           'aad-fam-uxd',
    'story-driven-delivery':            'aad-fam-sdd',
    'architecture-centric-engineering': 'aad-fam-arc',
    delivery:                           'aad-fam-delivery',
    'idea-shaping':                     'aad-fam-idea',
    'context-to-memory':                'aad-fam-ctm',
  };

  static familyFor(skillId: string): SkillFamily {
    return (CATALOG[skillId]?.family as SkillFamily) ?? 'architecture-centric-engineering';
  }

  static label(skillId: string): string {
    return CATALOG[skillId]?.label ?? skillId.replace(/^abd-/, '').replace(/-/g, ' ');
  }

  static familyCssClass(family: SkillFamily): string {
    return SkillCatalog.FAMILY_CSS[family];
  }
}
