"""
MapsContentAssembler — AGENTS.md + agents-staged + per-phase bundles (Instructions-based).

Writes:
  - Repo ``AGENTS.md`` and ``content/built/agents-staged.md`` (flat process + phases, solution preamble stripped)
  - ``content/parts/phases/built/<slug>.md`` (canonical for ``generate_prompt --mode static``)
  - ``content/built/phases/<slug>.md`` (same body; legacy path for existing links)
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from build_support import (
    demote_first_h1_to_h2,
    phase_fnames_from_skill_config,
    rewrite_links_for_agents_md,
    rewrite_links_for_phase_bundle,
    strip_operator_block_for_agents,
)
from instructions import _parts_dir
from maps_instructions import MapsInstructions


class _BuildTimeEngine:
    """Minimal engine surface for MapsInstructions when writing derived files (no workspace context)."""

    workspace_path = None
    context_paths: list = []


def load_skill_config(skill_root: Path) -> dict[str, Any]:
    p = skill_root / "skill-config.json"
    if not p.is_file():
        return {}
    return json.loads(p.read_text(encoding="utf-8"))


class MapsContentAssembler:
    def __init__(self, skill_root: Path, skill_config: dict[str, Any]):
        self.root = Path(skill_root).resolve()
        self.config = skill_config
        self.parts = _parts_dir(self.root)
        self.skill_name = skill_config.get("name", "abd-maps-models-specs")
        self._phase_fnames = phase_fnames_from_skill_config(skill_config)

    def _instructions(self) -> MapsInstructions:
        op = self.config.get("operation_sections", {})
        return MapsInstructions(op, self.root, _BuildTimeEngine(), self.config)

    def merge_agents_flat_body(self) -> str:
        """Process + phases in order; solution preamble stripped; links rewritten for skill root."""
        process_path = self.parts / "process.md"
        if not process_path.is_file():
            raise FileNotFoundError(f"Missing {process_path}")

        proc = process_path.read_text(encoding="utf-8")
        proc = demote_first_h1_to_h2(proc)
        proc = rewrite_links_for_agents_md(proc, self._phase_fnames)

        chunks: list[str] = [proc.rstrip(), "\n"]
        phases_dir = self.parts / "phases"

        for fname in self._phase_fnames:
            p = phases_dir / fname
            if not p.is_file():
                raise FileNotFoundError(f"Missing phase file: {p}")
            body = p.read_text(encoding="utf-8")
            body = strip_operator_block_for_agents(body)
            body = body.strip() + "\n"
            body = demote_first_h1_to_h2(body)
            body = rewrite_links_for_agents_md(body, self._phase_fnames)
            chunks.append("\n\n---\n\n")
            chunks.append(body)

        return "".join(chunks)

    def write_agents_and_staged(self) -> None:
        built = self.root / "content" / "built"
        built.mkdir(parents=True, exist_ok=True)
        body = self.merge_agents_flat_body()

        staged_path = built / "agents-staged.md"
        staged_path.write_text(
            "<!-- Generated by scripts/build.py — do not edit by hand. -->\n\n"
            "# Staged agent bundle\n\n"
            "Intermediate merge (process + phases, solution preamble stripped). "
            "Same markdown body as `AGENTS.md` below the title line.\n\n"
            "---\n\n"
            + body,
            encoding="utf-8",
        )
        print(f"Wrote {staged_path.relative_to(self.root)}", flush=True)

        agents_path = self.root / "AGENTS.md"
        agents_path.write_text(f"# AGENTS — {self.skill_name}\n\n" + body, encoding="utf-8")
        print(f"Wrote {agents_path.relative_to(self.root)}", flush=True)

    def write_built_phase_bundles(self) -> None:
        inst = self._instructions()
        cq_lib = self.config.get("critical_quality_library", "critical-quality-steps.md")

        primary_dir = self.parts / "phases" / "built"
        primary_dir.mkdir(parents=True, exist_ok=True)
        legacy_dir = self.root / "content" / "built" / "phases"
        legacy_dir.mkdir(parents=True, exist_ok=True)

        for slug in self.config.get("phase_files", []):
            text = inst.assemble_prompt(slug, include_context=False)
            text = rewrite_links_for_phase_bundle(text, self._phase_fnames)
            # One-line marker only so static file matches dynamic assembly (+ link rewrite) aside from this comment.
            full = "<!-- Generated by scripts/build.py — do not edit by hand. -->\n\n" + text

            p1 = primary_dir / f"{slug}.md"
            p1.write_text(full, encoding="utf-8")
            print(f"Wrote {p1.relative_to(self.root)}", flush=True)

            p2 = legacy_dir / f"{slug}.md"
            p2.write_text(full, encoding="utf-8")
            print(f"Wrote {p2.relative_to(self.root)}", flush=True)

        self._write_built_readmes(cq_lib)

    def _write_built_readmes(self, cq_lib: str) -> None:
        primary_readme = self.parts / "phases" / "built" / "README.md"
        primary_readme.write_text(
            "# Built phase bundles (`content/parts/phases/built/`)\n\n"
            "Each file is generated by **`scripts/build.py`** via **`MapsInstructions`** (same assembly as "
            "**`python scripts/generate_prompt.py --phase <slug> --mode dynamic`**). "
            "**`--mode static`** reads these files when present.\n\n"
            "Legacy copy: **`content/built/phases/<slug>.md`** (same bytes).\n\n"
            "Each bundle contains:\n\n"
            "1. **Solution analyst role** — `content/parts/solution-analyst-role.md` (headings demoted).\n"
            "2. **Rules** — `rules/*.md` filtered by YAML `phase_files` / `every_phase`.\n"
            "3. **Library** — excerpts per **`PHASE_LIBRARY_SLICES`** in **`skill-config.json`**.\n"
            "4. **Phase steps** — source `content/parts/phases/<slug>.md` only (no embedded role).\n"
            f"5. **Critical quality steps** — `content/parts/library/{cq_lib}` plus optional focus lines "
            "from **`phase_critical_quality_notes`** in **`skill-config.json`**.\n",
            encoding="utf-8",
        )
        print(f"Wrote {primary_readme.relative_to(self.root)}", flush=True)

        legacy_readme = self.root / "content" / "built" / "phases" / "README.md"
        legacy_readme.write_text(
            "# Built phase bundles (`content/built/phases/`)\n\n"
            "Generated by **`scripts/build.py`**. Canonical path for static prompts is "
            "**`content/parts/phases/built/`** (see that folder’s README).\n",
            encoding="utf-8",
        )
        print(f"Wrote {legacy_readme.relative_to(self.root)}", flush=True)
