// <SlugPascalCase>Stories.java
//
// Source of truth for stories in this leaf sub-epic.
// Generated by story-graph-ops `generate` command; safe to extend by hand.
//
// Structure mirrors the TypeScript format:
//   story      — display name
//   actor      — primary actor
//   acceptance_criteria — list of AC sequences (When/Then/And/But steps)
//   domain_terms        — key domain terms referenced in AC
//   evidence            — source pointers (one per AC)
//   named scenario objects — one per AC, containing the same steps

public final class <SlugPascalCase>Stories {

  // ===========================================================================
  // STORY: <Story Display Name>
  // ===========================================================================

  public static final class STORY_EXPORT_NAME {

    public static final String story = "<Story Display Name>";
    public static final String actor = "<Actor Name>";

    /**
     * Acceptance criteria — list of step sequences.
     *
     * Each inner list is one criterion:
     *   when  — trigger or precondition
     *   then  — primary observable outcome
     *   and   — additional outcomes in the same beat
     *   but   — what must NOT happen
     */
    public static final Object[][] acceptance_criteria = {
      {
        Map.of("when", "the *<Actor>* <triggering condition>"),
        Map.of("then", "the **<term>** <observable outcome>"),
        Map.of("and",  "<additional outcome>"),
      },
      {
        Map.of("when", "the *<Actor>* <alternate condition>"),
        Map.of("then", "<outcome>"),
        Map.of("but",  "the **<term>** <invariant that holds>"),
      },
    };

    public static final String[] domain_terms = { "<term 1>", "<term 2>" };
    public static final String[] evidence     = {
      "<source 1> — <location>",
      "<source 2> — <location>",
    };

    // -------------------------------------------------------------------------
    // Scenario: triggering condition observable outcome
    // -------------------------------------------------------------------------
    public static final Object[] triggeringConditionObservableOutcome = {
      Map.of("name", "<triggering condition> observable outcome"),
      Map.of("steps", new Object[]{
        Map.of("when", "the *<Actor>* <triggering condition>"),
        Map.of("then", "the **<term>** <observable outcome>"),
        Map.of("and",  "<additional outcome>"),
      }),
    };

    // -------------------------------------------------------------------------
    // Scenario: alternate condition outcome
    // -------------------------------------------------------------------------
    public static final Object[] alternateConditionOutcome = {
      Map.of("name", "<alternate condition> outcome"),
      Map.of("steps", new Object[]{
        Map.of("when", "the *<Actor>* <alternate condition>"),
        Map.of("then", "<outcome>"),
        Map.of("but",  "the **<term>** <invariant that holds>"),
      }),
    };
  }

  // ===========================================================================
  // STORY: <Second Story Display Name>
  // ===========================================================================

  public static final class SECOND_STORY_EXPORT_NAME {

    public static final String story = "<Second Story Display Name>";
    public static final String actor = "<Actor Name>";

    public static final Object[][] acceptance_criteria = {
      {
        Map.of("when", "the *<Actor>* <condition>"),
        Map.of("then", "the **<term>** <outcome>"),
      },
    };

    public static final String[] domain_terms = { "<term>" };
    public static final String[] evidence     = { "<source> — <location>" };

    public static final Object[] conditionOutcome = {
      Map.of("name", "<condition> outcome"),
      Map.of("steps", new Object[]{
        Map.of("when", "the *<Actor>* <condition>"),
        Map.of("then", "the **<term>** <outcome>"),
      }),
    };
  }
}
