// <slug>-stories.js
//
// Source of truth for stories in this leaf sub-epic.
// Generated by story-graph-ops `generate` command; safe to extend by hand.
// Re-run the generator to regenerate from story-graph.json.
//
// Note: use the TypeScript template (stories.ts) in TS projects — it adds
// `satisfies` checks for compile-time safety.

// =============================================================================
// BACKGROUND  (optional -- remove if no shared Given applies to this sub-epic)
// =============================================================================

export const BACKGROUND = [
  { given: '<shared precondition -- update or remove this block>' },
]

// =============================================================================
// STORY: <Story Display Name>
// =============================================================================

export const STORY_EXPORT_NAME = {
  story: '<Story Display Name>',
  actor: '<Actor Name>',

  acceptance_criteria: [
    [
      { when: 'the *<Actor>* <triggering condition>' },
      { then: 'the **<term>** <observable outcome>' },
      { and: '<additional outcome>' },
    ],
    [
      { when: 'the *<Actor>* <alternate condition>' },
      { then: '<outcome>' },
      { but: 'the **<term>** <invariant that holds>' },
    ],
  ],

  domain_terms: ['<term 1>', '<term 2>'],
  evidence: ['<source 1> — <location>', '<source 2> — <location>'],

  triggeringConditionObservableOutcome: {
    name: '<triggering condition> observable outcome',
    steps: [
      { when: 'the *<Actor>* <triggering condition>' },
      { then: 'the **<term>** <observable outcome>' },
      { and: '<additional outcome>' },
    ],
  },

  alternateConditionOutcome: {
    name: '<alternate condition> outcome',
    steps: [
      { when: 'the *<Actor>* <alternate condition>' },
      { then: '<outcome>' },
      { but: 'the **<term>** <invariant that holds>' },
    ],
  },
}

// =============================================================================
// STORY: <Second Story Display Name>
// =============================================================================

export const SECOND_STORY_EXPORT_NAME = {
  story: '<Second Story Display Name>',
  actor: '<Actor Name>',

  acceptance_criteria: [
    [
      { when: 'the *<Actor>* <condition>' },
      { then: 'the **<term>** <outcome>' },
    ],
  ],

  domain_terms: ['<term>'],
  evidence: ['<source> — <location>'],

  conditionOutcome: {
    name: '<condition> outcome',
    steps: [
      { when: 'the *<Actor>* <condition>' },
      { then: 'the **<term>** <outcome>' },
    ],
  },
}
