// <slug>-stories.ts
//
// Source of truth for stories in this leaf sub-epic.
// Generated by story-graph-ops `generate` command; safe to extend by hand.
// Re-run `bun run generate:stories` (or equivalent) to regenerate from story-graph.json.

import type { Step, AcceptanceCriterion, Background } from '<relative-path-to>/story-types'

// =============================================================================
// BACKGROUND  (optional -- remove if no shared Given applies to this sub-epic)
// =============================================================================

export const BACKGROUND = [
  { given: '<shared precondition -- update or remove this block>' },
] as const satisfies Background

// =============================================================================
// STORY: <Story Display Name>
// =============================================================================

export const STORY_EXPORT_NAME = {
  story: `<Story Display Name>`,
  actor: `<Actor Name>`,

  acceptance_criteria: [
    [
      { when: `the *<Actor>* <triggering condition>` },
      { then: `the **<term>** <observable outcome>` },
      { and: `<additional outcome>` },
    ],
    [
      { when: `the *<Actor>* <alternate condition>` },
      { then: `<outcome>` },
      { but: `the **<term>** <invariant that holds>` },
    ],
  ] as const satisfies readonly AcceptanceCriterion[],

  domain_terms: ['<term 1>', '<term 2>'] as const,
  evidence: ['<source 1> — <location>', '<source 2> — <location>'] as const,

  triggeringConditionObservableOutcome: {
    name: `<triggering condition> observable outcome`,
    steps: [
      { when: `the *<Actor>* <triggering condition>` },
      { then: `the **<term>** <observable outcome>` },
      { and: `<additional outcome>` },
    ] as const satisfies readonly Step[],
  },

  alternateConditionOutcome: {
    name: `<alternate condition> outcome`,
    steps: [
      { when: `the *<Actor>* <alternate condition>` },
      { then: `<outcome>` },
      { but: `the **<term>** <invariant that holds>` },
    ] as const satisfies readonly Step[],
  },

} as const

// =============================================================================
// STORY: <Second Story Display Name>
// =============================================================================

export const SECOND_STORY_EXPORT_NAME = {
  story: `<Second Story Display Name>`,
  actor: `<Actor Name>`,

  acceptance_criteria: [
    [
      { when: `the *<Actor>* <condition>` },
      { then: `the **<term>** <outcome>` },
    ],
  ] as const satisfies readonly AcceptanceCriterion[],

  domain_terms: ['<term>'] as const,
  evidence: ['<source> — <location>'] as const,

  conditionOutcome: {
    name: `<condition> outcome`,
    steps: [
      { when: `the *<Actor>* <condition>` },
      { then: `the **<term>** <outcome>` },
    ] as const satisfies readonly Step[],
  },

} as const
