#!/usr/bin/env python3
"""Convert a model-fidelity ``domain-model.md`` to ``domain-model.json``.

Usage::

    python md_domain_model_to_domain_graph.py <input.md> <output.json>

Format expected (generated by abd-domain-model skill — see
``practices/domain-driven-design/skills/abd-domain-model/templates/domain-model-template.md``)::

    # Module: [ModuleName]

    Scope: ...

    **Core terms**:
    - term1
    - term2

    ---

    # Core Domain

    ## **KaName**

    ### **KaName**            ← KA-anchor class (no stereotype at model fidelity)

    KaName(Type, Type)        ← constructor — types only, no param names, no `+` prefix
    ------
    propertyName: Type
    	Invariant: rule
    ----
    methodName(Type): ReturnType
    	CollaboratorType      ← optional, hidden collaborators BEFORE invariants
    	Invariant: rule
    - privateMethod(): Type   ← `-` prefix marks private (only visibility marker used)

    ### **ChildClass : ParentClass**

    ChildClass(Type)
    ------
    ----
    deltaMethod(Type): ReturnType

    ### references
    **Ref — title**
    Source: ...
    Locator: ...
    Extract: whole

    ### decisions made
    - rationale

    ---

    # Boundary Domain

    ### **BoundaryClass**

    ------
    ----
    methodName(Type): ReturnType

Differences from specification fidelity (see ``md_domain_specification_to_domain_graph.py``):
    - No ``+ ``/``- `` visibility prefix on properties; ``- `` only marks private methods.
    - Parameters are types only (``f(Type, Type): Ret``), not ``name: Type``.
    - No ``<< Stereotype >>`` markers on class headings.
    - No ``Interaction:`` blocks.
    - No phase headers like ``**Onboarding operations**:``.
    - Optional collaborator lines indented under operations before invariants.

Behaviour:
    - Reuses section / KA / refs / decisions splitting from the specification converter.
    - Parses class headers without stereotype expectations.
    - Lifts only what the model fidelity carries (no parameter names, no stereotypes,
      no phases, no interactions).
    - Exits with code 2 on unrecognised format; code 1 on validator rejection.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from domain_graph_file import validate_domain_model_dict  # noqa: E402
from md_domain_specification_to_domain_graph import (  # noqa: E402
    UnrecognisedFormatError,
    _DECISIONS_HEADER,
    _MODULE_HEADER,
    _REFERENCES_HEADER,
    _parse_decisions,
    _parse_module_heading,
    _parse_references,
    _split_kas,
    _split_top_sections,
    _strip_frontmatter,
)


# ---------------------------------------------------------------------------
# Format signature
# ---------------------------------------------------------------------------

_KA_HEADER = re.compile(r"^##\s+\*\*(.+?)\*\*\s*$", re.MULTILINE)
# Model-fidelity class header — name only, optional ``Child : Parent``.
_CLASS_HEADER = re.compile(r"^###\s+\*\*(?P<name>[^*]+?)\*\*\s*$", re.MULTILINE)
_EXTENDS_IN_NAME = re.compile(r"^(?P<child>\w+)\s*:\s*(?P<parent>\w+)\s*$")
_HORIZONTAL_RULE = re.compile(r"^-{3,}\s*$")

# Member-line shapes — no `+` prefix; optional `- ` for private methods.
_CONSTRUCTOR_LINE = re.compile(r"^(?P<name>[A-Z]\w*)\((?P<params>.*?)\)\s*$")
_OPERATION_LINE = re.compile(
    r"^(?P<vis>-\s+)?(?P<name>\w+)\((?P<params>.*?)\)\s*:\s*(?P<ret>.+?)\s*$"
)
_PROPERTY_LINE = re.compile(r"^(?P<name>\w+)\s*:\s*(?P<type>.+?)\s*$")
_INVARIANT_PREFIX = re.compile(r"^\s+Invariant:\s*(.+)$", re.IGNORECASE)
_COLLABORATOR_LINE = re.compile(r"^\s+(?P<type>[A-Z]\w*(?:<[^>]+>)?)\s*$")


# ---------------------------------------------------------------------------
# Type helpers
# ---------------------------------------------------------------------------


def _split_type_list(raw: str) -> List[str]:
    """Split ``Type, List<X>, Y`` honouring angle-bracket depth."""
    raw = raw.strip()
    if not raw:
        return []
    parts: List[str] = []
    depth = 0
    current: List[str] = []
    for ch in raw:
        if ch == "<":
            depth += 1
            current.append(ch)
        elif ch == ">":
            depth -= 1
            current.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current).strip())
    return [p for p in parts if p]


# ---------------------------------------------------------------------------
# Class-body parsing
# ---------------------------------------------------------------------------


def _collect_invariants_and_collaborators(
    lines: List[str], start: int
) -> Tuple[List[str], List[str], int]:
    """Return (invariants, collaborators, next_index) for indented lines after a member.

    Stops at the first non-indented line or any line starting with a recognised member.
    """
    invariants: List[str] = []
    collaborators: List[str] = []
    i = start
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        if not (line.startswith("\t") or line.startswith(" ")):
            break
        m_inv = _INVARIANT_PREFIX.match(line)
        if m_inv:
            invariants.append(m_inv.group(1).strip())
            i += 1
            continue
        m_collab = _COLLABORATOR_LINE.match(line)
        if m_collab:
            collaborators.append(m_collab.group("type").strip())
            i += 1
            continue
        # Unrecognised indented line — break (don't silently swallow content).
        break
    return invariants, collaborators, i


def _parse_class_header(header_line: str) -> Dict[str, Any]:
    """Parse ``### **Name**`` or ``### **Child : Parent**`` into a dict."""
    m = _CLASS_HEADER.match(header_line)
    if not m:
        raise UnrecognisedFormatError(f"bad class header: {header_line!r}")
    raw_name = m.group("name").strip()
    extends: Optional[str] = None
    em = _EXTENDS_IN_NAME.match(raw_name)
    if em:
        return {"name": em.group("child"), "extends": em.group("parent")}
    return {"name": raw_name, "extends": extends}


def _parse_class_body(body: str, class_name: str) -> Dict[str, Any]:
    """Parse a model-fidelity class body into constructor + properties + operations."""
    constructor: Dict[str, Any] = {"parameter_types": []}
    properties: List[Dict[str, Any]] = []
    operations: List[Dict[str, Any]] = []

    lines = body.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped or _HORIZONTAL_RULE.match(stripped):
            i += 1
            continue

        # Operation first — it has the `(...)` and `:` signature so it's most specific.
        m_op = _OPERATION_LINE.match(stripped)
        if m_op and m_op.group("name") != class_name:
            param_types = _split_type_list(m_op.group("params"))
            visibility = "private" if m_op.group("vis") else "public"
            invariants, collaborators, i = _collect_invariants_and_collaborators(
                lines, i + 1
            )
            op: Dict[str, Any] = {
                "name": m_op.group("name"),
                "parameter_types": param_types,
                "return_type": m_op.group("ret").strip(),
                "visibility": visibility,
                "collaborators": collaborators,
                "invariants": invariants,
            }
            operations.append(op)
            continue

        # Constructor — same shape as operation but no `: ReturnType`, and name == class
        m_ctor = _CONSTRUCTOR_LINE.match(stripped)
        if m_ctor and m_ctor.group("name") == class_name:
            constructor = {
                "parameter_types": _split_type_list(m_ctor.group("params"))
            }
            i += 1
            continue

        # Property — no `(...)`
        m_prop = _PROPERTY_LINE.match(stripped)
        if m_prop and "(" not in stripped:
            invariants, _collab, i = _collect_invariants_and_collaborators(
                lines, i + 1
            )
            properties.append(
                {
                    "name": m_prop.group("name"),
                    "return_type": m_prop.group("type").strip(),
                    "invariants": invariants,
                }
            )
            continue

        # Unrecognised line — skip. Validator surfaces any structural issue.
        i += 1

    return {
        "constructor": constructor,
        "properties": properties,
        "operations": operations,
    }


# ---------------------------------------------------------------------------
# KA + boundary parsing
# ---------------------------------------------------------------------------


def _split_ka_body(
    ka_body: str,
) -> Tuple[str, List[Tuple[str, str]], str, str]:
    """Return (ka_intro, class_blocks, references_section, decisions_section)."""
    refs_match = _REFERENCES_HEADER.search(ka_body)
    decisions_match = _DECISIONS_HEADER.search(ka_body)

    cutoff = len(ka_body)
    if refs_match:
        cutoff = min(cutoff, refs_match.start())
    if decisions_match:
        cutoff = min(cutoff, decisions_match.start())
    classes_region = ka_body[:cutoff]

    class_matches = list(_CLASS_HEADER.finditer(classes_region))
    if class_matches:
        ka_intro = classes_region[: class_matches[0].start()].strip()
    else:
        ka_intro = classes_region.strip()

    class_blocks: List[Tuple[str, str]] = []
    for idx, m in enumerate(class_matches):
        header_line = classes_region[m.start(): m.end()]
        body_start = m.end()
        body_end = (
            class_matches[idx + 1].start()
            if idx + 1 < len(class_matches)
            else len(classes_region)
        )
        class_blocks.append((header_line, classes_region[body_start:body_end]))

    refs_section = ""
    if refs_match:
        refs_end = (
            decisions_match.start()
            if (decisions_match and decisions_match.start() > refs_match.end())
            else len(ka_body)
        )
        refs_section = ka_body[refs_match.end():refs_end]

    decisions_section = ""
    if decisions_match:
        decisions_end = (
            refs_match.start()
            if (refs_match and refs_match.start() > decisions_match.end())
            else len(ka_body)
        )
        decisions_section = ka_body[decisions_match.end():decisions_end]

    return ka_intro, class_blocks, refs_section, decisions_section


def _parse_ka(ka_name: str, ka_body: str) -> Dict[str, Any]:
    """Parse a single ``## **KaName**`` block into a key_abstraction dict."""
    ka_intro, class_blocks, refs_section, decisions_section = _split_ka_body(ka_body)

    classes: List[Dict[str, Any]] = []
    for idx, (header_line, body) in enumerate(class_blocks):
        header = _parse_class_header(header_line)
        parsed = _parse_class_body(body, header["name"])
        classes.append(
            {
                "name": header["name"],
                "ka_anchor": idx == 0,
                "term": header["name"].lower(),
                "extends": header["extends"],
                "constructor": parsed["constructor"],
                "properties": parsed["properties"],
                "operations": parsed["operations"],
            }
        )

    return {
        "name": ka_name,
        "definition": ka_intro or f"{ka_name} key abstraction",
        "relationships": [],
        "classes": classes,
        "references": _parse_references(refs_section),
        "decisions": _parse_decisions(decisions_section),
    }


def _parse_boundary_domain(
    boundary_section: str, module_name: str
) -> Dict[str, Any]:
    """Parse ``# Boundary Domain`` into a boundary_domain dict."""
    refs_match = _REFERENCES_HEADER.search(boundary_section)
    decisions_match = _DECISIONS_HEADER.search(boundary_section)

    cutoff = len(boundary_section)
    if refs_match:
        cutoff = min(cutoff, refs_match.start())
    if decisions_match:
        cutoff = min(cutoff, decisions_match.start())
    classes_region = boundary_section[:cutoff]

    class_matches = list(_CLASS_HEADER.finditer(classes_region))
    intro = (
        classes_region[: class_matches[0].start()].strip()
        if class_matches
        else classes_region.strip()
    )
    intro = "\n".join(
        line for line in intro.splitlines() if not _HORIZONTAL_RULE.match(line.strip())
    ).strip()

    classes: List[Dict[str, Any]] = []
    for idx, m in enumerate(class_matches):
        header_line = classes_region[m.start(): m.end()]
        body_start = m.end()
        body_end = (
            class_matches[idx + 1].start()
            if idx + 1 < len(class_matches)
            else len(classes_region)
        )
        header = _parse_class_header(header_line)
        parsed = _parse_class_body(classes_region[body_start:body_end], header["name"])
        classes.append(
            {
                "name": header["name"],
                "owned_by": module_name,
                "term": header["name"].lower(),
                "extends": header["extends"],
                "constructor": parsed["constructor"],
                "properties": parsed["properties"],
                "operations": parsed["operations"],
            }
        )

    refs_section = ""
    if refs_match:
        refs_end = (
            decisions_match.start()
            if (decisions_match and decisions_match.start() > refs_match.end())
            else len(boundary_section)
        )
        refs_section = boundary_section[refs_match.end():refs_end]

    decisions_section = ""
    if decisions_match:
        decisions_end = (
            refs_match.start()
            if (refs_match and refs_match.start() > decisions_match.end())
            else len(boundary_section)
        )
        decisions_section = boundary_section[decisions_match.end():decisions_end]

    bd: Dict[str, Any] = {
        "relationships": [],
        "classes": classes,
        "references": _parse_references(refs_section),
        "decisions": _parse_decisions(decisions_section),
    }
    if intro:
        bd["intro"] = intro
    return bd


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------


def parse_model(md_path: Path) -> Dict[str, Any]:
    """Parse a model-fidelity ``domain-model.md`` into an ``abd-domain-model/v1`` dict."""
    text = md_path.read_text(encoding="utf-8")
    body, _frontmatter = _strip_frontmatter(text)

    if not _MODULE_HEADER.search(body):
        raise UnrecognisedFormatError(
            f"no '# Module: [...]' heading found in {md_path}"
        )
    if not _KA_HEADER.search(body):
        raise UnrecognisedFormatError(
            f"no '## **KaName**' headings found in {md_path}"
        )

    preamble, core_section, boundary_section = _split_top_sections(body)
    module_name, module_intro = _parse_module_heading(preamble)

    kas: List[Dict[str, Any]] = []
    for ka_name, ka_body in _split_kas(core_section):
        kas.append(_parse_ka(ka_name, ka_body))

    boundary_domain = (
        _parse_boundary_domain(boundary_section, module_name)
        if boundary_section.strip()
        else {"relationships": [], "classes": [], "references": [], "decisions": []}
    )

    module: Dict[str, Any] = {
        "name": module_name,
        "relationships": [],
        "key_abstractions": kas,
        "boundary_domain": boundary_domain,
    }
    if module_intro:
        module["intro"] = module_intro

    return {
        "schema": "abd-domain-model/v1",
        "product": module_name,
        "scope": module_intro.split("\n")[0][:200] if module_intro else module_name,
        "modules": [module],
    }


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main(argv: List[str] = sys.argv[1:]) -> int:
    if len(argv) != 2:
        print(
            "Usage: md_domain_model_to_domain_graph.py <input.md> <output.json>",
            file=sys.stderr,
        )
        return 1

    md_path = Path(argv[0])
    json_path = Path(argv[1])

    if not md_path.is_file():
        print(f"[ERROR] Markdown file not found: {md_path}", file=sys.stderr)
        return 1

    try:
        graph = parse_model(md_path)
    except UnrecognisedFormatError as exc:
        print(f"[FORMAT] {exc}", file=sys.stderr)
        return 2

    try:
        validate_domain_model_dict(graph)
    except ValueError as exc:
        json_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(
            json.dumps(graph, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        print(f"[INVALID] {exc}", file=sys.stderr)
        return 1

    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps(graph, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    module = graph["modules"][0]
    print(
        f"[PARSE] Module {module['name']!r}: "
        f"{len(module['key_abstractions'])} KAs, "
        f"{sum(len(ka['classes']) for ka in module['key_abstractions'])} core classes, "
        f"{len(module['boundary_domain']['classes'])} boundary classes",
        file=sys.stderr,
    )
    print(f"[WRITE] {json_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
