#!/usr/bin/env python3
"""Convert a specification-fidelity ``domain-specification.md`` to ``domain-model.json``.

Usage::

    python md_domain_specification_to_domain_graph.py <input.md> <output.json>

Format expected (generated by abd-domain-specification skill — see
``practices/domain-driven-design/skills/abd-domain-specification/reference/concepts.md``)::

    ---
    state: class-model
    ---

    # Module: [pml-my]

    Scope-or-intro paragraph for the module.

    ---

    # Core Domain

    ## **CustomerKa**

    KA intro paragraph.

    ### **Customer** << Entity >>

    Initialisation: optional one-liner describing how instances are bootstrapped.

    + Customer(email: EmailAddress, password: Password)
    ------
    + << composition >> identity: Identity
    + billing: Billing
        Invariant: billing.id must be present in self-care
    ----
    **Onboarding operations** (metadata.verified = false):

    + searchNumber(keyword: Keyword): List<NumberOption>
        Invariant: keyword is up to 5 characters
        Interaction:
            options = lookup.search(keyword)
            return options

    ### references
    **Ref — Title**
    Source: src/path/to/file.ts
    Locator: <symbol or line range>
    Extract: whole

    ### decisions made

    - decision text
    - another decision

    ---

    # Boundary Domain

    Optional boundary intro paragraph.

    ### **Cognito** << Service >> [Identity Provider — AWS IAM]

    Initialisation: optional initialisation note.
    ------
    ----
    + signUp(email: EmailAddress, password: Password): AccountToken

Behavior:
    - Parses the markdown into a validated ``abd-domain-model/v1`` dict.
    - Lifts all spec-only fields the schema supports (stereotype, stereotype_note,
      initialisation, named parameters on constructor/operations, operation phase,
      module intro, boundary_domain intro, references, decisions).
    - Synthesises a relationship at KA scope for every property whose markdown carried
      a ``<< composition | aggregation | association | produces >>`` stereotype prefix.
      ``<< produces >>`` is normalised to ``association``. Source-end role defaults to
      lowerCamelCase of the owning class name; target-end role is the property name;
      cardinality defaults to ``1..1`` both ends (the modeller refines later).
    - Exits with code 2 when the file does not match the format signature, so the
      caller can fall back to AI generation (mirrors ``md_thin_slice_to_story_graph``).
    - Exits with code 1 on validator rejection — the JSON is written first, then
      validated; a non-zero exit means the markdown needs a fix to match the schema.

Out of scope (deliberately, per P1.2 of the multi-backend plan):
    - Relationship promotion to module scope when both ends span different KAs.
    - Synthesising relationships from plain ``List<X>`` properties without a stereotype.
    - Round-trip back to markdown (that lives in a separate emitter script).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from domain_graph_file import validate_domain_model_dict  # noqa: E402


# ---------------------------------------------------------------------------
# Format signature
# ---------------------------------------------------------------------------

_FRONTMATTER = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_MODULE_HEADER = re.compile(r"^#\s+Module:\s*\[?(.+?)\]?\s*$", re.MULTILINE)
_KA_HEADER = re.compile(r"^##\s+\*\*(.+?)\*\*\s*$", re.MULTILINE)


class UnrecognisedFormatError(ValueError):
    """Raised when the markdown does not match the expected specification format."""


# ---------------------------------------------------------------------------
# Section splitting
# ---------------------------------------------------------------------------

_CORE_DOMAIN_HEADER = re.compile(r"^#\s+Core\s+Domain\s*$", re.MULTILINE)
_BOUNDARY_DOMAIN_HEADER = re.compile(r"^#\s+Boundary\s+Domain\s*$", re.MULTILINE)


def _strip_frontmatter(text: str) -> Tuple[str, Dict[str, str]]:
    """Return (body, frontmatter_dict). Frontmatter is optional."""
    m = _FRONTMATTER.match(text)
    if not m:
        return text, {}
    raw = m.group(1)
    fm: Dict[str, str] = {}
    for line in raw.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip()
    return text[m.end():], fm


def _split_top_sections(body: str) -> Tuple[str, str, str]:
    """Split body into (preamble, core_domain_section, boundary_domain_section).

    Preamble = everything before ``# Core Domain``.
    Boundary section may be empty.
    """
    core = _CORE_DOMAIN_HEADER.search(body)
    boundary = _BOUNDARY_DOMAIN_HEADER.search(body)
    if not core:
        return body, "", body[boundary.end():] if boundary else ""
    preamble = body[: core.start()]
    if boundary:
        core_section = body[core.end(): boundary.start()]
        boundary_section = body[boundary.end():]
    else:
        core_section = body[core.end():]
        boundary_section = ""
    return preamble, core_section, boundary_section


# ---------------------------------------------------------------------------
# Module heading + intro
# ---------------------------------------------------------------------------


def _parse_module_heading(preamble: str) -> Tuple[str, str]:
    """Return (module_name, module_intro). Module intro = paragraphs after heading."""
    m = _MODULE_HEADER.search(preamble)
    if not m:
        raise UnrecognisedFormatError(
            "no '# Module: [Name]' heading found in preamble"
        )
    name = m.group(1).strip()
    tail = preamble[m.end():]
    # Drop horizontal-rule lines and trailing whitespace; keep paragraph content
    intro_lines: List[str] = []
    for line in tail.splitlines():
        stripped = line.strip()
        if re.fullmatch(r"-{3,}", stripped):
            continue
        intro_lines.append(line)
    intro = "\n".join(intro_lines).strip()
    return name, intro


# ---------------------------------------------------------------------------
# KA splitting and parsing
# ---------------------------------------------------------------------------

_KA_SPLIT = re.compile(r"^##\s+\*\*(.+?)\*\*\s*$", re.MULTILINE)


def _split_kas(core_section: str) -> List[Tuple[str, str]]:
    """Return [(ka_name, ka_body), ...] in document order."""
    matches = list(_KA_SPLIT.finditer(core_section))
    if not matches:
        return []
    kas: List[Tuple[str, str]] = []
    for idx, m in enumerate(matches):
        name = m.group(1).strip()
        start = m.end()
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(core_section)
        kas.append((name, core_section[start:end]))
    return kas


# ---------------------------------------------------------------------------
# Class / references / decisions splitting within a KA
# ---------------------------------------------------------------------------

_CLASS_HEADER = re.compile(
    r"^###\s+\*\*(?P<name>[^*]+?)\*\*\s*"
    r"(?:<<\s*(?P<stereotype>\w+)\s*>>)?\s*"
    r"(?:\[(?P<note>[^\]]+)\])?\s*$",
    re.MULTILINE,
)
_REFERENCES_HEADER = re.compile(r"^###\s+references\s*$", re.MULTILINE | re.IGNORECASE)
_DECISIONS_HEADER = re.compile(
    r"^###\s+decisions(?:\s+made)?\s*$", re.MULTILINE | re.IGNORECASE
)


def _split_ka_body(
    ka_body: str,
) -> Tuple[str, List[Tuple[str, str]], str, str]:
    """Return (ka_intro, class_blocks, references_section, decisions_section).

    ``class_blocks`` is a list of (class_header_line, class_body) tuples in order.
    """
    refs_match = _REFERENCES_HEADER.search(ka_body)
    decisions_match = _DECISIONS_HEADER.search(ka_body)

    # The "classes region" runs from the start to whichever of references/decisions
    # appears first (or end-of-body if neither).
    cutoff = len(ka_body)
    if refs_match:
        cutoff = min(cutoff, refs_match.start())
    if decisions_match:
        cutoff = min(cutoff, decisions_match.start())
    classes_region = ka_body[:cutoff]

    # KA intro = text before the first class header in the classes region.
    class_matches = list(_CLASS_HEADER.finditer(classes_region))
    if class_matches:
        ka_intro = classes_region[: class_matches[0].start()].strip()
    else:
        ka_intro = classes_region.strip()

    class_blocks: List[Tuple[str, str]] = []
    for idx, m in enumerate(class_matches):
        header_line = classes_region[m.start(): m.end()]
        body_start = m.end()
        body_end = (
            class_matches[idx + 1].start()
            if idx + 1 < len(class_matches)
            else len(classes_region)
        )
        class_blocks.append((header_line, classes_region[body_start:body_end]))

    refs_section = ""
    if refs_match:
        refs_end = decisions_match.start() if (
            decisions_match and decisions_match.start() > refs_match.end()
        ) else len(ka_body)
        refs_section = ka_body[refs_match.end():refs_end]

    decisions_section = ""
    if decisions_match:
        decisions_end = refs_match.start() if (
            refs_match and refs_match.start() > decisions_match.end()
        ) else len(ka_body)
        decisions_section = ka_body[decisions_match.end():decisions_end]

    return ka_intro, class_blocks, refs_section, decisions_section


# ---------------------------------------------------------------------------
# Class heading parsing
# ---------------------------------------------------------------------------

_EXTENDS_IN_NAME = re.compile(r"^(?P<child>\w+)\s*:\s*(?P<parent>\w+)\s*$")


def _parse_class_header(header_line: str) -> Dict[str, Any]:
    """Parse ``### **Name** << Stereotype >> [note]`` into a dict.

    Returns dict with: name, extends (or None), stereotype (or None),
    stereotype_note (or None).
    """
    m = _CLASS_HEADER.match(header_line)
    if not m:
        raise UnrecognisedFormatError(f"bad class header: {header_line!r}")
    raw_name = m.group("name").strip()
    extends: Optional[str] = None
    em = _EXTENDS_IN_NAME.match(raw_name)
    if em:
        name = em.group("child")
        extends = em.group("parent")
    else:
        name = raw_name
    stereotype = m.group("stereotype") or None
    note = m.group("note")
    stereotype_note = note.strip() if note else None
    return {
        "name": name,
        "extends": extends,
        "stereotype": stereotype,
        "stereotype_note": stereotype_note,
    }


# ---------------------------------------------------------------------------
# Class body parsing — initialisation, constructor, properties, operations
# ---------------------------------------------------------------------------

_HORIZONTAL_RULE = re.compile(r"^-{3,}\s*$")
_INITIALISATION = re.compile(r"^Initialisation:\s*(.+)$", re.IGNORECASE)
_PHASE_HEADER = re.compile(r"^\*\*([\w\- ]+)\s+operations\*\*\s*(?:\(.*?\))?\s*:\s*$")
_NOTE_PREFIX = re.compile(r"^\s+Note:\s*(.+)$", re.IGNORECASE)
_INVARIANT_PREFIX = re.compile(r"^\s+Invariant:\s*(.+)$", re.IGNORECASE)
_INTERACTION_HEADER = re.compile(r"^\s+Interaction:\s*$", re.IGNORECASE)

# Member-line shapes (line starts with + or -)
_PROPERTY_LINE = re.compile(
    r"^(?P<vis>[+-])\s+"
    r"(?:<<\s*(?P<rel>[\w]+)\s*>>\s*)?"
    r"(?P<name>\w+)\s*:\s*(?P<type>.+?)\s*$"
)
_OPERATION_LINE = re.compile(
    r"^(?P<vis>[+-])\s+(?P<name>\w+)\((?P<params>.*?)\)\s*:\s*(?P<ret>.+?)\s*$"
)
_CONSTRUCTOR_LINE = re.compile(
    r"^(?P<vis>[+-])\s+(?P<name>[A-Z]\w*)\((?P<params>.*?)\)\s*$"
)


def _vis(prefix: str) -> str:
    return "public" if prefix == "+" else "private"


def _split_params(raw: str) -> List[Dict[str, str]]:
    """Split a parameter string like ``a: T, b: List<X, Y>`` honouring angle-bracket depth."""
    raw = raw.strip()
    if not raw:
        return []
    parts: List[str] = []
    depth = 0
    current: List[str] = []
    for ch in raw:
        if ch == "<":
            depth += 1
            current.append(ch)
        elif ch == ">":
            depth -= 1
            current.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current).strip())

    result: List[Dict[str, str]] = []
    for part in parts:
        if ":" in part:
            name, _, typ = part.partition(":")
            result.append({"name": name.strip(), "type": typ.strip()})
        elif part:
            # Unnamed param — keep type only, name auto-generated for visibility
            result.append({"name": f"arg{len(result)}", "type": part.strip()})
    return result


def _collect_attached_block(
    lines: List[str], start: int
) -> Tuple[Dict[str, Any], int]:
    """Collect Invariant / Interaction / Note lines indented under a member at ``start``.

    Returns (block_dict, next_index). ``block_dict`` has keys ``invariants``,
    ``interaction``, ``notes`` (each possibly empty).
    """
    invariants: List[str] = []
    interaction: List[str] = []
    notes: List[str] = []
    i = start
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        # Stop at the next non-indented line — that's the next member or a phase header.
        if not (line.startswith("\t") or line.startswith("    ") or line.startswith(" ")):
            break
        # Stop if line starts with + or - at any indent (treat as next member).
        stripped = line.lstrip()
        if stripped.startswith(("+ ", "- ")):
            break
        m_inv = _INVARIANT_PREFIX.match(line)
        if m_inv:
            invariants.append(m_inv.group(1).strip())
            i += 1
            continue
        m_note = _NOTE_PREFIX.match(line)
        if m_note:
            notes.append(m_note.group(1).strip())
            i += 1
            continue
        if _INTERACTION_HEADER.match(line):
            i += 1
            interaction = _collect_interaction_block(lines, i)
            # Skip the lines we just consumed
            i = _skip_interaction_block(lines, i)
            continue
        # Unrecognised indented line — break to be safe (could be next phase header).
        break
    return {
        "invariants": invariants,
        "interaction": interaction,
        "notes": notes,
    }, i


def _interaction_indent(line: str) -> int:
    """Count leading whitespace as visual columns (tab = 4)."""
    cols = 0
    for ch in line:
        if ch == "\t":
            cols += 4
        elif ch == " ":
            cols += 1
        else:
            break
    return cols


def _collect_interaction_block(lines: List[str], start: int) -> List[str]:
    """Read interaction body lines (deeper indent than ``Interaction:`` header)."""
    body: List[str] = []
    if start >= len(lines):
        return body
    # First non-blank line establishes the body indent.
    body_indent: Optional[int] = None
    for i in range(start, len(lines)):
        line = lines[i]
        if not line.strip():
            continue
        ind = _interaction_indent(line)
        if body_indent is None:
            body_indent = ind
        if ind < body_indent:
            break
        body.append(line.strip())
    return body


def _skip_interaction_block(lines: List[str], start: int) -> int:
    """Return the index just past the interaction block that begins at ``start``."""
    if start >= len(lines):
        return start
    body_indent: Optional[int] = None
    i = start
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        ind = _interaction_indent(line)
        if body_indent is None:
            body_indent = ind
        if ind < body_indent:
            return i
        i += 1
    return i


def _parse_class_body(
    body: str,
    class_name: str,
) -> Dict[str, Any]:
    """Parse a class body into initialisation + constructor + properties + operations + rels."""
    initialisation: Optional[str] = None
    constructor: Dict[str, Any] = {"parameter_types": []}
    properties: List[Dict[str, Any]] = []
    operations: List[Dict[str, Any]] = []
    synthesised_relationships: List[Dict[str, Any]] = []

    lines = body.splitlines()
    i = 0
    current_phase: Optional[str] = None
    # Tracks whether we have moved past the constructor / properties separator into operations.
    # Not used to enforce ordering — purely advisory.

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        m_init = _INITIALISATION.match(stripped)
        if m_init:
            initialisation = m_init.group(1).strip()
            i += 1
            continue

        if _HORIZONTAL_RULE.match(stripped):
            i += 1
            continue

        m_phase = _PHASE_HEADER.match(stripped)
        if m_phase:
            current_phase = m_phase.group(1).strip().lower()
            i += 1
            continue

        m_op = _OPERATION_LINE.match(stripped)
        if m_op and m_op.group("name") != class_name:
            params = _split_params(m_op.group("params"))
            op: Dict[str, Any] = {
                "name": m_op.group("name"),
                "parameter_types": [p["type"] for p in params],
                "parameters": params,
                "return_type": m_op.group("ret").strip(),
                "visibility": _vis(m_op.group("vis")),
                "collaborators": [],
                "invariants": [],
            }
            if current_phase:
                op["phase"] = current_phase
            attached, i = _collect_attached_block(lines, i + 1)
            if attached["invariants"]:
                op["invariants"] = attached["invariants"]
            if attached["interaction"]:
                op["interaction"] = attached["interaction"]
            if attached["notes"]:
                op["note"] = "\n".join(attached["notes"])
            operations.append(op)
            continue

        m_ctor = _CONSTRUCTOR_LINE.match(stripped)
        if m_ctor and m_ctor.group("name") == class_name:
            params = _split_params(m_ctor.group("params"))
            constructor = {
                "parameter_types": [p["type"] for p in params],
                "parameters": params,
            }
            i += 1
            continue

        m_prop = _PROPERTY_LINE.match(stripped)
        if m_prop:
            rel_kind = m_prop.group("rel")
            prop: Dict[str, Any] = {
                "name": m_prop.group("name"),
                "return_type": m_prop.group("type").strip(),
                "invariants": [],
            }
            attached, i = _collect_attached_block(lines, i + 1)
            if attached["invariants"]:
                prop["invariants"] = attached["invariants"]
            if attached["interaction"]:
                prop["interaction"] = attached["interaction"]
            if attached["notes"]:
                prop["note"] = "\n".join(attached["notes"])
            properties.append(prop)
            if rel_kind:
                synthesised_relationships.append(
                    _synthesise_relationship(class_name, prop["name"], prop["return_type"], rel_kind)
                )
            continue

        # Unrecognised line — skip silently. (Mismatch will surface in validator.)
        i += 1

    out: Dict[str, Any] = {
        "constructor": constructor,
        "properties": properties,
        "operations": operations,
        "synthesised_relationships": synthesised_relationships,
    }
    if initialisation:
        out["initialisation"] = initialisation
    return out


_KIND_NORMALISE = {
    "composition": "composition",
    "aggregation": "aggregation",
    "association": "association",
    "produces": "association",
}


def _camel(name: str) -> str:
    return name[:1].lower() + name[1:] if name else name


def _strip_list_wrapper(type_text: str) -> str:
    """``List<Foo>`` -> ``Foo``; ``Foo`` -> ``Foo``."""
    m = re.match(r"^\s*List<\s*(.+?)\s*>\s*$", type_text)
    return m.group(1) if m else type_text.strip()


def _is_cardinality_many(type_text: str) -> bool:
    return type_text.strip().startswith("List<")


def _synthesise_relationship(
    source_class: str, property_name: str, property_type: str, rel_kind: str
) -> Dict[str, Any]:
    """Build a relationship entry from a ``<< kind >>`` prefix on a property."""
    kind = _KIND_NORMALISE.get(rel_kind.lower(), "association")
    target_class = _strip_list_wrapper(property_type)
    target_card = "0..*" if _is_cardinality_many(property_type) else "1..1"
    return {
        "name": property_name,
        "kind": kind,
        "ends": [
            {
                "class": source_class,
                "role": _camel(source_class),
                "cardinality": "1..1",
            },
            {
                "class": target_class,
                "role": property_name,
                "cardinality": target_card,
            },
        ],
    }


# ---------------------------------------------------------------------------
# References + decisions parsing
# ---------------------------------------------------------------------------

_REF_BLOCK = re.compile(
    r"^\*\*Ref\s*[—-]\s*(?P<title>.+?)\*\*\s*\n"
    r"Source:\s*(?P<source>.+?)\s*\n"
    r"Locator:\s*(?P<locator>.+?)\s*\n"
    r"Extract:\s*(?P<extract>.+?)\s*$",
    re.MULTILINE,
)


def _parse_references(section: str) -> List[Dict[str, str]]:
    refs: List[Dict[str, str]] = []
    for m in _REF_BLOCK.finditer(section):
        refs.append(
            {
                "title": m.group("title").strip(),
                "source": m.group("source").strip().strip("`"),
                "locator": m.group("locator").strip(),
                "extract": m.group("extract").strip(),
            }
        )
    return refs


_DECISION_BULLET = re.compile(r"^-\s+(.+?)\s*$")


def _parse_decisions(section: str) -> List[str]:
    decisions: List[str] = []
    buffer: List[str] = []
    for line in section.splitlines():
        m = _DECISION_BULLET.match(line)
        if m:
            if buffer:
                decisions.append(" ".join(buffer).strip())
                buffer = []
            buffer.append(m.group(1).strip())
        elif buffer and line.startswith((" ", "\t")):
            buffer.append(line.strip())
        elif buffer and not line.strip():
            decisions.append(" ".join(buffer).strip())
            buffer = []
    if buffer:
        decisions.append(" ".join(buffer).strip())
    return decisions


# ---------------------------------------------------------------------------
# Boundary domain parsing
# ---------------------------------------------------------------------------


def _parse_boundary_domain(
    boundary_section: str, module_name: str
) -> Dict[str, Any]:
    """Parse the ``# Boundary Domain`` section into a boundary_domain dict."""
    refs_match = _REFERENCES_HEADER.search(boundary_section)
    decisions_match = _DECISIONS_HEADER.search(boundary_section)

    cutoff = len(boundary_section)
    if refs_match:
        cutoff = min(cutoff, refs_match.start())
    if decisions_match:
        cutoff = min(cutoff, decisions_match.start())
    classes_region = boundary_section[:cutoff]

    class_matches = list(_CLASS_HEADER.finditer(classes_region))
    intro = (
        classes_region[: class_matches[0].start()].strip()
        if class_matches
        else classes_region.strip()
    )
    # Drop trailing horizontal rules from the intro.
    intro = "\n".join(
        line for line in intro.splitlines() if not _HORIZONTAL_RULE.match(line.strip())
    ).strip()

    classes: List[Dict[str, Any]] = []
    for idx, m in enumerate(class_matches):
        header_line = classes_region[m.start(): m.end()]
        body_start = m.end()
        body_end = (
            class_matches[idx + 1].start()
            if idx + 1 < len(class_matches)
            else len(classes_region)
        )
        body = classes_region[body_start:body_end]
        header = _parse_class_header(header_line)
        parsed = _parse_class_body(body, header["name"])
        # Boundary classes do NOT contribute synthesised relationships at KA scope
        # (they have no KA). Discard them.
        cls: Dict[str, Any] = {
            "name": header["name"],
            "owned_by": module_name,
            "term": header["name"].lower(),
            "extends": header["extends"],
            "constructor": parsed["constructor"],
            "properties": parsed["properties"],
            "operations": parsed["operations"],
        }
        if header["stereotype"]:
            cls["stereotype"] = header["stereotype"]
        if header["stereotype_note"]:
            cls["stereotype_note"] = header["stereotype_note"]
        if "initialisation" in parsed:
            cls["initialisation"] = parsed["initialisation"]
        classes.append(cls)

    refs_section = ""
    if refs_match:
        refs_end = (
            decisions_match.start()
            if (decisions_match and decisions_match.start() > refs_match.end())
            else len(boundary_section)
        )
        refs_section = boundary_section[refs_match.end():refs_end]

    decisions_section = ""
    if decisions_match:
        decisions_end = (
            refs_match.start()
            if (refs_match and refs_match.start() > decisions_match.end())
            else len(boundary_section)
        )
        decisions_section = boundary_section[decisions_match.end():decisions_end]

    bd: Dict[str, Any] = {
        "relationships": [],
        "classes": classes,
        "references": _parse_references(refs_section),
        "decisions": _parse_decisions(decisions_section),
    }
    if intro:
        bd["intro"] = intro
    return bd


# ---------------------------------------------------------------------------
# KA parsing — top-level
# ---------------------------------------------------------------------------


def _parse_ka(ka_name: str, ka_body: str) -> Dict[str, Any]:
    """Parse a single ``## **KaName**`` block into a key_abstraction dict."""
    ka_intro, class_blocks, refs_section, decisions_section = _split_ka_body(ka_body)

    classes: List[Dict[str, Any]] = []
    synthesised: List[Dict[str, Any]] = []
    for idx, (header_line, body) in enumerate(class_blocks):
        header = _parse_class_header(header_line)
        parsed = _parse_class_body(body, header["name"])
        cls: Dict[str, Any] = {
            "name": header["name"],
            "ka_anchor": idx == 0,
            "term": header["name"].lower(),
            "extends": header["extends"],
            "constructor": parsed["constructor"],
            "properties": parsed["properties"],
            "operations": parsed["operations"],
        }
        if header["stereotype"]:
            cls["stereotype"] = header["stereotype"]
        if header["stereotype_note"]:
            cls["stereotype_note"] = header["stereotype_note"]
        if "initialisation" in parsed:
            cls["initialisation"] = parsed["initialisation"]
        classes.append(cls)
        synthesised.extend(parsed["synthesised_relationships"])

    return {
        "name": ka_name,
        "definition": ka_intro or f"{ka_name} key abstraction",
        "relationships": synthesised,
        "classes": classes,
        "references": _parse_references(refs_section),
        "decisions": _parse_decisions(decisions_section),
    }


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------


def parse_specification(md_path: Path) -> Dict[str, Any]:
    """Parse a ``domain-specification.md`` file into an ``abd-domain-model/v1`` dict."""
    text = md_path.read_text(encoding="utf-8")
    body, _frontmatter = _strip_frontmatter(text)

    if not _MODULE_HEADER.search(body):
        raise UnrecognisedFormatError(
            f"no '# Module: [...]' heading found in {md_path}"
        )
    if not _KA_HEADER.search(body):
        raise UnrecognisedFormatError(
            f"no '## **KaName**' headings found in {md_path}"
        )

    preamble, core_section, boundary_section = _split_top_sections(body)
    module_name, module_intro = _parse_module_heading(preamble)

    kas: List[Dict[str, Any]] = []
    for ka_name, ka_body in _split_kas(core_section):
        kas.append(_parse_ka(ka_name, ka_body))

    boundary_domain = (
        _parse_boundary_domain(boundary_section, module_name)
        if boundary_section.strip()
        else {"relationships": [], "classes": [], "references": [], "decisions": []}
    )

    module: Dict[str, Any] = {
        "name": module_name,
        "relationships": [],
        "key_abstractions": kas,
        "boundary_domain": boundary_domain,
    }
    if module_intro:
        module["intro"] = module_intro

    return {
        "schema": "abd-domain-model/v1",
        "product": module_name,
        "scope": module_intro.split("\n")[0][:200] if module_intro else module_name,
        "modules": [module],
    }


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main(argv: List[str] = sys.argv[1:]) -> int:
    if len(argv) != 2:
        print(
            "Usage: md_domain_specification_to_domain_graph.py "
            "<input.md> <output.json>",
            file=sys.stderr,
        )
        return 1

    md_path = Path(argv[0])
    json_path = Path(argv[1])

    if not md_path.is_file():
        print(f"[ERROR] Markdown file not found: {md_path}", file=sys.stderr)
        return 1

    try:
        graph = parse_specification(md_path)
    except UnrecognisedFormatError as exc:
        print(f"[FORMAT] {exc}", file=sys.stderr)
        return 2

    try:
        validate_domain_model_dict(graph)
    except ValueError as exc:
        # Write the unvalidated JSON so the operator can inspect what was lifted,
        # then surface the validator error with a clear exit code.
        json_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(
            json.dumps(graph, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        print(f"[INVALID] {exc}", file=sys.stderr)
        return 1

    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps(graph, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    module = graph["modules"][0]
    print(
        f"[PARSE] Module {module['name']!r}: "
        f"{len(module['key_abstractions'])} KAs, "
        f"{sum(len(ka['classes']) for ka in module['key_abstractions'])} core classes, "
        f"{len(module['boundary_domain']['classes'])} boundary classes",
        file=sys.stderr,
    )
    print(f"[WRITE] {json_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
